### ISSUE TITLE
Saved loans page will not load on first attempt

### ISSUE THREAD

**Issue by UtuRaiden** [Yasmeeeenn/finance-fusion#47]

**Comment by UtuRaiden** [comment]
Upon the first click it will give the wrong page error. Then it will work afterwards. Gives error bellow 

Uncaught Error: Rendered more hooks than during the previous render.
    at updateWorkInProgressHook (react-dom.development.js:16507:13)
    at updateReducer (react-dom.development.js:16568:14)
    at updateState (react-dom.development.js:17004:10)
    at Object.useState (react-dom.development.js:17915:16)
    at Object.useState (react.development.js:1622:21)
    at useMutation (useMutation.ts:39:37)
    at savedLoans (SavedLoans.jsx:41:24)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateFunctionComponent (react-dom.development.js:19588:20)
    at beginWork (react-dom.development.js:21601:16)
